// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class CaseSummary
{
    public int CaseId { get; set; }

    public int CustomerId { get; set; }

    public string CustomerItemCode { get; set; }

    public string CustomerItemDesc { get; set; }

    public int MonthId { get; set; }

    public string OurItemCode { get; set; }

    public decimal Cases { get; set; }
}