// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class ExceptionLog
{
    public int LogId { get; set; }

    public string LogMessage { get; set; }

    public string LogStackTrace { get; set; }

    public DateTime AddedOn { get; set; }
}