// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Invoice_Logic.Data.EF;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Invoice_Logic.Data.EF
{
    public partial interface IInvoice_ContextProcedures
    {
        Task<int> ProcessInvoicesAsync(int? headerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
