// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Invoice_Logic.Data.EF;

public partial class Invoice_Context : DbContext
{
    public Invoice_Context(DbContextOptions<Invoice_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<CaseSummary> CaseSummaries { get; set; }

    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

    public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }

    public virtual DbSet<InvoiceResult> InvoiceResults { get; set; }

    public virtual DbSet<PriceDeal> PriceDeals { get; set; }

    public virtual DbSet<ResultStatusType> ResultStatusTypes { get; set; }

    public virtual DbSet<StatusType> StatusTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CaseSummary>(entity =>
        {
            entity.HasKey(e => e.CaseId);

            entity.ToTable("CaseSummary");

            entity.Property(e => e.Cases).HasColumnType("numeric(18, 2)");
            entity.Property(e => e.CustomerItemCode)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.CustomerItemDesc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OurItemCode)
                .IsRequired()
                .HasMaxLength(15);
        });

        modelBuilder.Entity<InvoiceDetail>(entity =>
        {
            entity.ToTable("InvoiceDetail");

            entity.Property(e => e.ApprovedRate).HasColumnType("numeric(18, 2)");
            entity.Property(e => e.Cases).HasColumnType("numeric(18, 2)");
            entity.Property(e => e.CustItemCode)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.CustItemDesc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CustomerRate).HasColumnType("numeric(18, 2)");

            entity.HasOne(d => d.InvoiceHeader).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.InvoiceHeaderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceDetail_InvoiceHeader");
        });

        modelBuilder.Entity<InvoiceHeader>(entity =>
        {
            entity.ToTable("InvoiceHeader");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000);

            entity.HasOne(d => d.StatusType).WithMany(p => p.InvoiceHeaders)
                .HasForeignKey(d => d.StatusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceHeader_StatusType");
        });

        modelBuilder.Entity<InvoiceResult>(entity =>
        {
            entity.ToTable("InvoiceResult");

            entity.Property(e => e.CasesRemaining).HasColumnType("numeric(18, 2)");
            entity.Property(e => e.OurItemCode)
                .IsRequired()
                .HasMaxLength(15);

            entity.HasOne(d => d.InvoiceDetail).WithMany(p => p.InvoiceResults)
                .HasForeignKey(d => d.InvoiceDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceResult_InvoiceDetail");

            entity.HasOne(d => d.ResultStatusType).WithMany(p => p.InvoiceResults)
                .HasForeignKey(d => d.ResultStatusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceResult_ResultStatusType");
        });

        modelBuilder.Entity<PriceDeal>(entity =>
        {
            entity.HasKey(e => e.PriceDealId).HasName("PK__PriceDea__F0B2B9A7E50270FC");

            entity.Property(e => e.ItemCode)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.Rate).HasColumnType("numeric(18, 2)");
        });

        modelBuilder.Entity<ResultStatusType>(entity =>
        {
            entity.ToTable("ResultStatusType");

            entity.Property(e => e.ResultStatusTypeId).ValueGeneratedNever();
            entity.Property(e => e.ResultStatusTypeDesc)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<StatusType>(entity =>
        {
            entity.ToTable("StatusType");

            entity.Property(e => e.StatusTypeId).ValueGeneratedNever();
            entity.Property(e => e.StatusTypeDesc)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}