// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class InvoiceHeader
{
    public int InvoiceHeaderId { get; set; }

    public int Customer { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public int StatusTypeId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    public virtual StatusType StatusType { get; set; }
}