// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Invoice_Logic.Data.EF;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Invoice_Logic.Data.EF
{
    public partial class Invoice_Context
    {
        private IInvoice_ContextProcedures _procedures;

        public virtual IInvoice_ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Invoice_ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IInvoice_ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Invoice_ContextProcedures : IInvoice_ContextProcedures
    {
        private readonly Invoice_Context _context;

        public Invoice_ContextProcedures(Invoice_Context context)
        {
            _context = context;
        }

        public virtual async Task<int> ProcessInvoicesAsync(int? headerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "headerId",
                    Value = headerId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[ProcessInvoices] @headerId = @headerId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
