// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class InvoiceResult
{
    public int InvoiceResultId { get; set; }

    public int InvoiceDetailId { get; set; }

    public int InvoiceHeaderId { get; set; }

    public string OurItemCode { get; set; }

    public decimal CasesRemaining { get; set; }

    public bool HasFailedCase { get; set; }

    public bool HasFailedRate { get; set; }

    public int ResultStatusTypeId { get; set; }

    public virtual InvoiceDetail InvoiceDetail { get; set; }

    public virtual ResultStatusType ResultStatusType { get; set; }
}