// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class InvoiceDetail
{
    public int InvoiceDetailId { get; set; }

    public int InvoiceHeaderId { get; set; }

    public string CustItemCode { get; set; }

    public string CustItemDesc { get; set; }

    public decimal CustomerRate { get; set; }

    public decimal ApprovedRate { get; set; }

    public decimal Cases { get; set; }

    public virtual InvoiceHeader InvoiceHeader { get; set; }

    public virtual ICollection<InvoiceResult> InvoiceResults { get; set; } = new List<InvoiceResult>();
}