// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class PriceDeal
{
    public int PriceDealId { get; set; }

    public string ItemCode { get; set; }

    public string StructureId { get; set; }

    public int Customer { get; set; }

    public decimal Rate { get; set; }

    public int EffectiveMonth { get; set; }

    public int EndMonth { get; set; }
}