// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Invoice_Logic.Data.EF;

public partial class ResultStatusType
{
    public int ResultStatusTypeId { get; set; }

    public string ResultStatusTypeDesc { get; set; }

    public virtual ICollection<InvoiceResult> InvoiceResults { get; set; } = new List<InvoiceResult>();
}